[[redirects]]
  from = "https://watermarkktp.netlify.app/*"
  to = "https://watermarkktp.com/:splat"
  status = 301
  force = true

[[headers]]
  for = "/*"
  [headers.value]
    Cache-Control = "public, max-age=3600"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"

[[headers]]
  for = "/*.css"
  [headers.value]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.value]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jpg"
  [headers.value]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.png"
  [headers.value]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.svg"
  [headers.value]
    Cache-Control = "public, max-age=31536000"